---
title: "Visium Spatial Tx - ratio Spatial/ISOG/ISO counting"
author: '[Kevin Lebrigand](mailto:lebrigand@ipmc.cnrs.fr) CNRS Senior Scientist - Computational Biology'
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '3'
  html_notebook:
    code_folding: none
    theme: journal
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

<style type="text/css">

body, td {
   font-size: 15px;
}
code.r{
  font-size: 15px;
}
pre {
  font-size: 15px
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  cache = FALSE,
  cache.lazy = FALSE,
  tidy = TRUE
)
```

# mob164315

```{r message=FALSE, warning=FALSE, echo=TRUE, eval=T, fig.height=4, fig.width=6}

setwd("/data/10x_data/10x_visium/")
source("00.import.R")

mob164315 <- readRDS("./output/mob164315.nanopore.rds")
SpatialDimPlot(mob164315, label = TRUE, label.size = 3, pt.size.factor =2)
col=ggplotColours(n = length(unique(mob164315@active.ident)))

SpatialFeaturePlot(mob164315, features = c("nCount_Spatial","nCount_ISOG","nCount_ISO"), pt.size.factor = 2, alpha = c(0.1, 1))

mob164315[['ratio_spatial_isog']] <- log(mob164315@meta.data$nCount_Spatial/mob164315@meta.data$nCount_ISOG,2)
SpatialFeaturePlot(mob164315, features = c("ratio_spatial_isog"), pt.size.factor = 2, alpha = c(0.1, 1))

mob164315[['ratio_isog_iso']] <- log(mob164315@meta.data$nCount_ISOG/mob164315@meta.data$nCount_ISO,2)
SpatialFeaturePlot(mob164315, features = c("ratio_isog_iso"), pt.size.factor = 2, alpha = c(0.1, 1))

DefaultAssay(mob164315) <- "Spatial"
x <- rownames(mob164315@assays$Spatial@counts[grep("Rna", rownames(mob164315@assays$Spatial@counts)),])

mob164315 <- AddModuleScore(mob164315, list(x), name="rnase")
print(x)
DotPlot(mob164315,features=x) + RotatedAxis()

VlnPlot(mob164315, features=c("ratio_spatial_isog","ratio_isog_iso"))

p1 <- SpatialDimPlot(mob164315, label = TRUE, label.size = 3, pt.size.factor =2)
p2 <- ggplot(data=mob164315@meta.data, aes(x=rnase1,y=ratio_isog_iso)) +  geom_point(shape = 21, colour = "black", fill = col[mob164315@meta.data$ClusterName]) +
      theme_bw() + theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank())
plot_grid(p1,p2)

```

# hip142078

```{r message=FALSE, warning=FALSE, echo=TRUE, eval=T, fig.height=4, fig.width=6}


#cat("barcode,id\n", file="identity.csv")
#write.table(hip142078@active.ident, file="identity.csv", sep=",", col.names = F, append=TRUE)

hip142078 <- readRDS("./output/hip142078.nanopore.rds")
SpatialDimPlot(hip142078, label = TRUE, label.size = 3, pt.size.factor =2)
col=ggplotColours(n = length(unique(hip142078@active.ident)))

SpatialFeaturePlot(hip142078, features = c("nCount_Spatial","nCount_ISOG","nCount_ISO"), pt.size.factor = 2, alpha = c(0.1, 1))

p1 <- ggplot(data=hip142078@meta.data, aes(x=nCount_Spatial,y=nCount_ISOG)) +  geom_point(shape = 21, colour = "black", fill = col[hip142078@meta.data$ClusterName]) +
      theme_bw() + theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank())
p2 <- ggplot(data=hip142078@meta.data, aes(x=nCount_ISOG,y=nCount_ISO)) +  geom_point(shape = 21, colour = "black", fill = col[hip142078@meta.data$ClusterName]) +
      theme_bw() + theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank())
plot_grid(p1,p2)

hip142078[['ratio_spatial_isog']] <- log(hip142078@meta.data$nCount_Spatial/hip142078@meta.data$nCount_ISOG,2)
hip142078[['ratio_isog_iso']] <- log(hip142078@meta.data$nCount_ISOG/hip142078@meta.data$nCount_ISO,2)
SpatialFeaturePlot(hip142078, features = c("ratio_spatial_isog","ratio_isog_iso"), pt.size.factor = 2, alpha = c(0.1, 1))

DefaultAssay(hip142078) <- "Spatial"
x <- rownames(hip142078@assays$Spatial@counts[grep("Rna", rownames(hip142078@assays$Spatial@counts)),])

hip142078 <- AddModuleScore(hip142078, list(x), name="rnase")
print(x)
DotPlot(hip142078,features=x) + RotatedAxis()

SpatialFeaturePlot(hip142079, features = c("rnase1"), pt.size.factor = 2, alpha = c(0.1, 1))


VlnPlot(hip142078, features=c("ratio_spatial_isog","ratio_isog_iso"))

p1 <- SpatialDimPlot(hip142078, label = TRUE, label.size = 3, pt.size.factor =2)
p2 <- ggplot(data=hip142078@meta.data, aes(x=rnase1,y=ratio_isog_iso)) +  geom_point(shape = 21, colour = "black", fill = col[hip142078@meta.data$ClusterName]) +
      theme_bw() + theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank())
plot_grid(p1,p2)

VlnPlot(hip142078, features=c("percent.mito","percent.ribo"))

```

# hip142079

```{r message=FALSE, warning=FALSE, echo=TRUE, eval=T, fig.height=4, fig.width=6}

hip142079 <- readRDS("./output/hip142079.nanopore.rds")
SpatialDimPlot(hip142079, label = TRUE, label.size = 3, pt.size.factor =2)
col=ggplotColours(n = length(unique(hip142079@active.ident)))

SpatialFeaturePlot(hip142079, features = c("nCount_Spatial","nCount_ISOG","nCount_ISO"), pt.size.factor = 2, alpha = c(0.1, 1))

p1 <- ggplot(data=hip142079@meta.data, aes(x=nCount_Spatial,y=nCount_ISOG)) +  geom_point(shape = 21, colour = "black", fill = col[hip142079@meta.data$ClusterName]) +
      theme_bw() + theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank())
p2 <- ggplot(data=hip142079@meta.data, aes(x=nCount_ISOG,y=nCount_ISO)) +  geom_point(shape = 21, colour = "black", fill = col[hip142079@meta.data$ClusterName]) +
      theme_bw() + theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank())
plot_grid(p1,p2)



hip142079[['ratio_spatial_isog']] <- log(hip142079@meta.data$nCount_Spatial/hip142079@meta.data$nCount_ISOG,2)
hip142079[['ratio_isog_iso']] <- log(hip142079@meta.data$nCount_ISOG/hip142079@meta.data$nCount_ISO,2)
SpatialFeaturePlot(hip142079, features = c("ratio_spatial_isog","ratio_isog_iso"), pt.size.factor = 2, alpha = c(0.1, 1))

DefaultAssay(hip142079) <- "Spatial"
x <- rownames(hip142079@assays$Spatial@counts[grep("Rna", rownames(hip142079@assays$Spatial@counts)),])
print(x)

hip142079 <- AddModuleScore(hip142079, list(x), name="rnase")
DotPlot(hip142079,features=x) + RotatedAxis()

VlnPlot(hip142079, features=c("ratio_spatial_isog","ratio_isog_iso"))

p1 <- SpatialDimPlot(hip142079, label = TRUE, label.size = 3, pt.size.factor =2)
p2 <- ggplot(data=hip142079@meta.data, aes(x=rnase1,y=ratio_isog_iso)) +  geom_point(shape = 21, colour = "black", fill = col[hip142079@meta.data$ClusterName]) +
      theme_bw() + theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank())
plot_grid(p1,p2)

VlnPlot(hip142079, features=c("percent.mito","percent.ribo"))

```

# genes by genes

```{r message=FALSE, warning=FALSE, echo=TRUE, eval=T, fig.height=4, fig.width=6}

hip142079 <- readRDS("./output/hip142079.nanopore.rds")

common <- intersect(rownames(hip142079@assays$Spatial@data), rownames(hip142079@assays$ISOG@data))
thalamus <- WhichCells(hip142079, ident="Thalamus")

x <- as.data.frame(Matrix::rowSums(hip142079@assays$Spatial@counts[,thalamus]))
y <- as.data.frame(Matrix::rowSums(hip142079@assays$ISOG@counts[,thalamus]))

df <- merge(x,y,by=0,all=T)
colnames(df) <- c("Rownames","spatial","isog")
head(df)
df$A <- log((df$spatial+df$isog)/2,2)
df$M <- log(((df$spatial+1)/(df$isog+1)),2)
head(df)
df$id <- rownames(df)
write.table(df, file="df.csv", sep=",")

ggplot(data=df, aes(x=A,y=M)) +  geom_point(shape = 21, colour = "black", fill = "black") +
      theme_bw() + theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank()) +
      geom_text_repel(data=subset(df, df$spatial > 1000 & df$M > 5), aes(label=id), size=3) +
      geom_point(data=subset(df, df$Spatial > 1000 & df$M > 5), col="red")

write.table(df, file="df.csv", sep=",")




# CALY-202 (758) in Dg
DefaultAssay(hip142079) <- "ISO"
x <- rownames(hip142079@assays$ISO@counts[grep("Caly", rownames(hip142079@assays$ISO@counts)),])
x
SpatialFeaturePlot(hip142079, features = x, pt.size.factor = 2, alpha = c(0.1, 1))


```

# Session Info

```{r sessinf}
sessionInfo()
```

