---
title: "SiT - Supplementary Figure 02"
author: '[Kevin Lebrigand](mailto:lebrigand@ipmc.cnrs.fr)§, Joseph Bergenstråhle §, Kim Thrane §, Annelie Mollbrink, Pascal Barbry, Rainer Waldmann and Joakim Lundeberg'
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
abstract: 'The spatial landscape of gene expression isoforms in tissue sections.'
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '3'
  html_notebook:
    code_folding: none
    theme: journal
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

<style type="text/css">

body, td {
   font-size: 15px;
}
code.r{
  font-size: 15px;
}
pre {
  font-size: 15px
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  cache = FALSE,
  cache.lazy = FALSE,
  tidy = TRUE
)

```

```{r message=FALSE, warning=FALSE, echo=TRUE, eval=T, fig.height=4, fig.width=6}

setwd("thisdir")
source("00.common.import.R")

MOB <- readRDS("data/MOB.nanopore.rds")
CBS1 <- readRDS("data/CBS1.nanopore.rds")
CBS2 <- readRDS("data/CBS2.nanopore.rds")

clusters <- c("Midbrain","Hippocampus area","Isocortex-1","Isocortex-2","Olfactory area","Fiber tracts","Retrosplenial area","CA1/CA2","Thalamus","Hypothalamus","CA3","DG")

tiff("figures/Figure.sup.02a.tif", units="in", width=6, height=8, res=300)
agreement = read.delim("data/RNAgree.txt", sep="\t", stringsAsFactors = F)
ggplot(data=agreement, aes(x=RN, y=Agreement)) +
    geom_line()+
    geom_point()
dev.off()

tiff("figures/Figure.sup.02b.tif", units="in", width=6, height=8, res=300)
agreement = read.delim("data/QVAgree.txt", sep="\t", stringsAsFactors = F)
ggplot(data=agreement, aes(x=QV, y=Agreement)) +
    geom_line()+
  theme_minimal() +
    geom_point()
dev.off()

```

# Session Info

```{r sessinf}
sessionInfo()
```

