---
title: "SiT - Figures"
author: '[Kevin Lebrigand](mailto:lebrigand@ipmc.cnrs.fr)§, Joseph Bergenstråhle §, Kim Thrane §, Annelie Mollbrink, Pascal Barbry, Rainer Waldmann and Joakim Lundeberg'
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
abstract: 'The spatial landscape of gene expression isoforms in tissue sections.'
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '3'
  html_notebook:
    code_folding: none
    theme: journal
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

<style type="text/css">

body, td {
   font-size: 15px;
}
code.r{
  font-size: 15px;
}
pre {
  font-size: 15px
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  cache = FALSE,
  cache.lazy = FALSE,
  tidy = TRUE
)

```

```{r message=FALSE, warning=FALSE, echo=TRUE, eval=T, fig.height=4, fig.width=6}

setwd("/data/10x_data/10x_visium/000-github/000-publish/")
source("00.common.import.R")

MOB <- readRDS("../output/MOB.nanopore.rds")

```

# markers

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=6, fig.width=8}

pdf("Fig.2a.pdf", width=8, height=6, useDingbats=FALSE)
SpatialDimPlot(MOB)
dev.off()

DefaultAssay(object = MOB) <- "Spatial"
#markers <- FindAllMarkers(object = MOB, only.pos = TRUE)
#top <- markers %>% group_by(cluster) %>% top_n(25, avg_log2FC)
#DoHeatmap(MOB, features=top$gene, size=3.5)
avg <- AverageExpression(MOB, return.seurat=TRUE, assays="Spatial")
#pheatmap(avg@assays$Spatial@scale.data[top$gene,], cluster_rows=FALSE, cluster_cols=FALSE, fontsize = 8, clustering_method = "complete")
genes <- c("Nrgn","Meis2","Mbp","Slc32a1","Bin1","Spp1","Ntng1","Shisa3","Slc17a7","Scn1b","Cnot3","Bc1","Slc1a2","Tatdn1","Lrrc17","Nrsn1","Th","Vsnl1","Shisa9","Eomes","Cldn5","Mgp","Apod","Apoe","Fabp7")

pdf("Fig.2a-2.pdf", width=8, height=8, useDingbats=FALSE)
pheatmap(avg@assays$Spatial@scale.data[genes,], cluster_rows=FALSE, cluster_cols=FALSE, fontsize = 8, clustering_method = "complete")
dev.off()

pdf("Fig.2a-3.pdf", width=8, height=8, useDingbats=FALSE)
SpatialFeaturePlot(MOB,c("Nrgn","Spp1","Cnot3","Nrsn1","Cldn5"),ncol=5)
dev.off()

```

# Plp1

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=6, fig.width=8}

x <- unique(rownames(MOB@assays$ISO@data)[grep(paste("^Plp1..",sep=""), rownames(MOB@assays$ISO@data))])
DefaultAssay(MOB) <- "ISO"

pdf("Fig.2c.pdf", width=10, height=6, useDingbats=FALSE)
SpatialFeaturePlot(MOB, features = x, pt.size.factor=1.8, alpha = c(1, 1))
dev.off()

```

# Integration of external data (Tepe et al., Cell report, 2018) (GSE121891)

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=6, fig.width=8}

tepe <- readRDS("tepe.WT.rds")

p1 <- DimPlot(tepe, group.by = "ClusterName", label=TRUE)
DefaultAssay(tepe) <- "RNA"
p2 <- DotPlot(tepe,feature="Plp1", group.by="ClusterName")

pdf("Fig.2e.pdf", width=8, height=6, useDingbats=FALSE)
plot_grid(p1,p2)
dev.off()

# Plp1 expresser cell types
a <- aggregate(tepe@assays$RNA@counts["Plp1",], list(tepe@meta.data$ClusterName), sum)
a$nb <- as.data.frame(table(tepe@meta.data$ClusterName))$Freq
a$avg <- a$x/a$nb
plp1_cell_types <- as.character(a[a$avg>1,]$Group.1)

# ---------------------------
# Spotlight deconvolution
# --------------------------

#Seurat::Idents(object = tepe) <- tepe@meta.data$ClusterName
#cluster_markers_all <- Seurat::FindAllMarkers(object = tepe, 
#                                              assay = "SCT",
#                                              slot = "data",
#                                              verbose = TRUE, 
#                                              only.pos = TRUE)

#saveRDS(object = cluster_markers_all, file = here::here("markers_tepe.rds"))

#set.seed(123)
#spotlight_ls <- spotlight_deconvolution(
#  se_sc = tepe,
#  counts_spatial = MOB@assays$Spatial@counts,
#  clust_vr = "ClusterName", # Variable in sc_seu containing the cell-type annotation
#  cluster_markers = cluster_markers_all, # Dataframe with the marker genes
#  cl_n = 100, # number of cells per cell type to use
#  hvg = 3000, # Number of HVG to use
#  ntop = NULL, # How many of the marker genes to use (by default all)
#  transf = "uv", # Perform unit-variance scaling per cell and spot prior to factorzation and NLS
#  method = "nsNMF", # Factorization method
#  min_cont = 0 # Remove those cells contributing to a spot below a certain threshold 
#)

#saveRDS(object = spotlight_ls, file = here::here("spotlight_tepe.rds"))
spotlight_ls <- readRDS("spotlight_tepe.rds")

nmf_mod <- spotlight_ls[[1]]
decon_mtrx <- spotlight_ls[[2]]

h <- NMF::coef(nmf_mod[[1]])
rownames(h) <- paste("Topic", 1:nrow(h), sep = "_")
#topic_profile_plts <- SPOTlight::dot_plot_profiles_fun(
#  h = h,
#  train_cell_clust = nmf_mod[[2]])

#topic_profile_plts[[2]] + ggplot2::theme(
#  axis.text.x = ggplot2::element_text(angle = 90), 
#  axis.text = ggplot2::element_text(size = 12))

#topic_profile_plts[[1]] + theme(axis.text.x = element_text(angle = 90), 
#                                axis.text = element_text(size = 12))

basis_spotlight <- data.frame(NMF::basis(nmf_mod[[1]]))

colnames(basis_spotlight) <- unique(stringr::str_wrap(nmf_mod[[2]], width = 30))

#basis_spotlight %>%
#  dplyr::arrange(desc(MyOligo)) %>%
#  round(., 5) %>% 
#  DT::datatable(., filter = "top")

#######################################################
# remove contributing cell types under 8% --> this is usefull for scatterpie spotlight plot not to have too many contributing cells
# we could keep all contributions for latter correlation computation, tested, improve a bit but message is the same so keep that standard filtering
# except for SiTx visualisation this gives much nicer representation
#######################################################
decon_mtrx_sub <- decon_mtrx[, colnames(decon_mtrx) != "res_ss"]
#decon_mtrx_sub[decon_mtrx_sub < 0.08] <- 0
decon_mtrx <- cbind(decon_mtrx_sub, "res_ss" = decon_mtrx[, "res_ss"])
rownames(decon_mtrx) <- colnames(MOB)

decon_df <- decon_mtrx %>%
  data.frame() %>%
  tibble::rownames_to_column("barcodes")

MOB@meta.data <- MOB@meta.data %>%
  tibble::rownames_to_column("barcodes") %>%
  dplyr::left_join(decon_df, by = "barcodes") %>%
  tibble::column_to_rownames("barcodes")

Seurat::SpatialFeaturePlot(
  object = MOB,
  features = plp1_cell_types,
  alpha = c(0.1, 1),
  pt.size.factor = 2.5)

SPOTlight::spatial_scatterpie(se_obj = MOB,
                              cell_types_all = plp1_cell_types,
                              img_path = "/data/10x_data/10x_visium/illumina/MOB/spatial/tissue_lowres_image.png",
                              pie_scale = 0.6)

col=as.data.frame(ggplotColours(n = length(unique(tepe@meta.data$ClusterName))))
col$cell_type <- levels(tepe@meta.data$ClusterName)
colnames(col) <- c("color","celltype")
col

col <- col[col$celltype %in% plp1_cell_types,]

pdf("Fig.2f.pdf", width=8, height=6, useDingbats=FALSE)
SPOTlight::spatial_scatterpie(se_obj = MOB,
                              cell_types_all = plp1_cell_types,
                              img_path = "/data/10x_data/10x_visium/illumina/MOB/spatial/tissue_lowres_image.png",
                              pie_scale = 0.5, scatterpie_alpha = 2)  +
                              scale_fill_manual(values = col[, "color"], breaks = plp1_cell_types)
dev.off()

v <- numeric()
v2 <- numeric()
for(i in 1:length(plp1_cell_types)){
  df <- data.frame()
  x <- cor.test(MOB@meta.data[,plp1_cell_types[i]],MOB@assays$ISO@data["Plp1..ENSMUST00000033800.12",])$estimate
  x2 <- cor.test(MOB@meta.data[,plp1_cell_types[i]],MOB@assays$ISO@data["Plp1..ENSMUST00000113085.1",])$estimate
  v <- c(v, x)
  v2 <- c(v2, x2)
}
df <- as.data.frame(cbind(v,v2))
rownames(df) <- plp1_cell_types
colnames(df) <- c("Plp1-201","Plp1-202")

pheatmap(df, cluster_rows=TRUE, cluster_cols=FALSE, fontsize = 8, clustering_method = "complete", clustering_distance_rows = "manhattan")

df$id <- rownames(df)
df <- melt(df,id.vars = "id")

pdf("Fig.2f-2.pdf", width=16, height=10, useDingbats=FALSE)
ggplot(data=df, aes(x=id, y=value, fill=variable)) +
  geom_bar(stat="identity", position=position_dodge())+
  #geom_text(aes(label=variable), vjust=1.6, color="white",
  #          position = position_dodge(0.9), size=3.5)+
  scale_fill_manual(values=c("#ff0000", "#ff9015")) +
  theme_minimal()
dev.off()

```

# Myl6

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=6, fig.width=8}

DefaultAssay(tepe) <- "RNA"
DotPlot(tepe,feature="Myl6", group.by="ClusterName")

# Myl6 expresser cell types
a <- aggregate(tepe@assays$RNA@counts["Myl6",], list(tepe@meta.data$ClusterName), sum)
a$nb <- as.data.frame(table(tepe@meta.data$ClusterName))$Freq
a$avg <- a$x/a$nb
barplot(a)
myl6_cell_types <- as.character(a[a$avg>1,]$Group.1)

x <- unique(rownames(MOB@assays$ISO@data)[grep(paste("^Myl6..",sep=""), rownames(MOB@assays$ISO@data))])
x <- c("Myl6..ENSMUST00000164181.1","Myl6..ENSMUST00000218127.1")
DefaultAssay(MOB) <- "ISO"

#pdf("Fig.2c.pdf", width=10, height=6, useDingbats=FALSE)
SpatialFeaturePlot(MOB, features = x, pt.size.factor=1.8, alpha = c(1, 1))
#dev.off()

cell_types_all <- colnames(decon_mtrx)[which(colnames(decon_mtrx) != "res_ss")]

v <- numeric()
v2 <- numeric()
for(i in 1:length(cell_types_all)){
  df <- data.frame()
  x <- cor.test(MOB@meta.data[,cell_types_all[i]],MOB@assays$ISO@data["Myl6..ENSMUST00000164181.1",])$estimate
  x2 <- cor.test(MOB@meta.data[,cell_types_all[i]],MOB@assays$ISO@data["Myl6..ENSMUST00000218127.1",])$estimate
  v <- c(v, x)
  v2 <- c(v2, x2)
}
df <- as.data.frame(cbind(v,v2))
rownames(df) <- cell_types_all
colnames(df) <- c("Myl6-201","Myl6-206")

pheatmap(df, cluster_rows=TRUE, cluster_cols=FALSE, fontsize = 8, clustering_method = "complete", clustering_distance_rows = "manhattan")

df$id <- rownames(df)
df <- melt(df,id.vars = "id")

#pdf("Fig.2f-2.pdf", width=16, height=10, useDingbats=FALSE)
ggplot(data=df, aes(x=id, y=value, fill=variable)) +
  geom_bar(stat="identity", position=position_dodge())+
  #geom_text(aes(label=variable), vjust=1.6, color="white",
  #          position = position_dodge(0.9), size=3.5)+
  scale_fill_manual(values=c("#ff0000", "#ff9015")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

#dev.off()

Seurat::SpatialFeaturePlot(
  object = MOB,
  features = c("N10","OEC4"),
  alpha = c(0.1, 1),
  pt.size.factor = 2.5)

VlnPlot(MOB,c("Myl6..ENSMUST00000164181.1","Myl6..ENSMUST00000218127.1"))


```

# Session Info

```{r sessinf}
sessionInfo()
```

