---
title: "SiT - Figures"
author: '[Kevin Lebrigand](mailto:lebrigand@ipmc.cnrs.fr)§, Joseph Bergenstråhle §, Kim Thrane §, Annelie Mollbrink, Pascal Barbry, Rainer Waldmann and Joakim Lundeberg'
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
abstract: 'The spatial landscape of gene expression isoforms in tissue sections.'
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '3'
  html_notebook:
    code_folding: none
    theme: journal
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

<style type="text/css">

body, td {
   font-size: 15px;
}
code.r{
  font-size: 15px;
}
pre {
  font-size: 15px
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  cache = FALSE,
  cache.lazy = FALSE,
  tidy = TRUE
)

```

```{r message=FALSE, warning=FALSE, echo=TRUE, eval=T, fig.height=4, fig.width=6}

setwd("thisdir")
source("00-common.import.R")

CBS2 <- readRDS("output/CBS2.nanopore.deconv.rds")

pdf("figures/Figure.main.1.pdf", width=6, height=6, useDingbats=FALSE)
SpatialDimPlot(CBS2, pt.size.factor=1.6)
SpatialFeaturePlot(CBS2, feature="Snap25")

DefaultAssay(CBS2) <- "ISO"
x <- c("Snap25..ENSMUST00000028727.10","Snap25..ENSMUST00000110098.3")
SpatialFeaturePlot(CBS2, features = x, pt.size.factor=1.5, alpha = c(1, 1), max.cutoff = c(3.5,3.5))

SpatialFeaturePlot(CBS2, features = "AtoI_ratio", pt.size.factor=1.6, alpha = c(1, 1), max.cutoff = c(0.4))

dev.off()

```

# Session Info

```{r sessinf}
sessionInfo()
```

