---
title: "Visium Spatial Tx - Mouse Hippocampus (hip142078) - 02.nanopore"
author: '[Kevin Lebrigand](mailto:lebrigand@ipmc.cnrs.fr) CNRS Senior Scientist - Computational Biology'
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '3'
  html_notebook:
    code_folding: none
    theme: journal
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

<style type="text/css">

body, td {
   font-size: 15px;
}
code.r{
  font-size: 15px;
}
pre {
  font-size: 15px
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  cache = FALSE,
  cache.lazy = FALSE,
  tidy = TRUE
)

```

# Loading Spatial data

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=4, fig.width=6}

setwd("/data/10x_data/10x_visium/")
source("00.import.R")

hip142078 <- readRDS("./output/hip142078.rds")
clusters <- c("Midbrain", "Hippocampus", "Isocortex-1", "Isocortex-2", "Olfactory area", "Fiber tracts", "Isocortex-3", "Hammons horn", "Isocortex-4", "Thalamus", "Hypothalamus", "Ca3", "Dg", "Outside")

```

# Add Nanopore data: ISO, ISOG, JUNC and EDIT assays, scale_my_data

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=6, fig.width=8}

all = read.delim("./nanopore/hip142078_genematrix.txt", stringsAsFactors = F)
data = all[,2:ncol(all)]
colnames(data) <- paste(colnames(data),"-1", sep="")
rownames(data) <- all$geneId
vect <- colnames(hip142078@assays$Spatial)
data <- data[vect]
hip142078[["ISOG"]] <- CreateAssayObject(counts = data)
hip142078 <- NormalizeData(object = hip142078, assay = "ISOG")
hip142078 <- ScaleData(object = hip142078, assay = "ISOG")

all = read.delim("./nanopore/hip142078_isomatrix.txt", stringsAsFactors = F)
data = all[,4:ncol(all)]
dim(data)
colnames(data) <- paste(colnames(data),"-1", sep="")
rownames(data) = paste(all$geneId, all$transcriptId, sep="..")
vect <- colnames(hip142078@assays$Spatial)
idx <- grep("undef", rownames(data), invert = TRUE)
data <- data[idx,vect]
dim(data)
hip142078[["ISO"]] <- CreateAssayObject(counts = data)
hip142078 <- NormalizeData(object = hip142078, assay = "ISO")
hip142078 <- scale_my_data(hip142078, assay="ISO")

all = read.delim("./nanopore/hip142078_juncmatrix.txt", stringsAsFactors = F)
data = all[,2:ncol(all)]
dim(data)
colnames(data) <- paste(colnames(data),"-1", sep="")
rownames(data) = str_replace(all$junctionId, ":", "..")
vect <- colnames(hip142078@assays$Spatial)
data <- data[,vect]
data <- data[which(Matrix::rowSums(data)>9),]
dim(data)
hip142078[["JUNC"]] <- CreateAssayObject(counts = data)
hip142078 <- NormalizeData(object = hip142078, assay = "JUNC")
hip142078 <- scale_my_data(hip142078, assay="JUNC")

all = read.delim("./nanopore/hip142078.snp100838.RN3.QV5_snpmatrix.full.txt", stringsAsFactors = F)
data = all[,4:ncol(all)]
dim(data)
colnames(data) <- paste(colnames(data),"-1", sep="")
rownames(data) = paste(all$geneId, all$transcriptId, sep=":")
vect <- colnames(hip142078@assays$Spatial)
#idx <- grep("intergenic", rownames(data), invert = TRUE)
#data <- data[idx,vect]
#idx <- grep("Rik", rownames(data), invert = TRUE)
data <- data[,vect]
idx1 <- grep("\\.\\.A", rownames(data))
idx2 <- grep("\\.\\.G", rownames(data))
data <- data[c(idx1,idx2),]
dim(data)

x <- unique(sapply(strsplit(rownames(data), "\\.\\."), `[`, 1))
countA <- data[grep("\\.\\.A",rownames(data)),]
colnames(countA) <- colnames(data)
rownames(countA) <- x
countG <- data[grep("\\.\\.G",rownames(data)),]
colnames(countG) <- colnames(data)
rownames(countG) <- x
ratio <- countG/(countA+countG)

hip142078[['AtoI_A']] <- Matrix::colSums(countA)
hip142078[['AtoI_G']] <- Matrix::colSums(countG)
hip142078[['AtoI_total']] <- hip142078[['AtoI_A']]+hip142078[['AtoI_G']]
hip142078[['AtoI_ratio']] <- hip142078[['AtoI_G']]/hip142078[['AtoI_total']]
hip142078[['AtoI_detected']] <- Matrix::colSums(countG > 0)

hip142078[["AtoI"]] <- CreateAssayObject(counts = countA)
hip142078 <- SetAssayData(hip142078, slot = "data", as.matrix(countG), assay = "AtoI")
hip142078 <- SetAssayData(hip142078, slot = "scale.data", as.matrix(ratio), assay = "AtoI")

saveRDS(hip142078, "./output/hip142078.nanopore.rds")

```

# Session Info

```{r sessinf}
sessionInfo()
```

