---
title: "Visium Spatial Tx - Mouse Olfactory Bulb (MOB164315) - 01.spatial"
author: '[Kevin Lebrigand](mailto:lebrigand@ipmc.cnrs.fr) CNRS Senior Scientist - Computational Biology'
date: 'Compiled: `r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '3'
  html_notebook:
    code_folding: none
    theme: journal
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

<style type="text/css">

body, td {
   font-size: 15px;
}
code.r{
  font-size: 15px;
}
pre {
  font-size: 15px
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  cache = FALSE,
  cache.lazy = FALSE,
  tidy = TRUE
)
```

# Loading Spatial data

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=4, fig.width=6}

setwd("/data/10x_data/10x_visium/")
source("00.import.R")

mob164315 <- Load10X_Spatial(data.dir = "/data/10x_data/000-notebooks/visium/164315-visium-ob")

#ribo.genes <- grep(pattern = "^Rp[sl]", x = rownames(data))
#mito.genes <- grep(pattern = "^mt-", x = rownames(data))
#data <- data[-c(ribo.genes,mito.genes),]

VlnPlot(mob164315, features = c("nCount_Spatial","nFeature_Spatial"), pt.size = 0.1) + NoLegend() + ggtitle("mob164315 nCount_Spatial")
SpatialFeaturePlot(mob164315, features = c("nCount_Spatial","nFeature_Spatial"), max.cutoff = 30000, pt.size.factor = 2) + 
  theme(legend.position = "right") + 
  ggtitle("mob164315 nCount_Spatial")

```

# Quality control, no filtration

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=6, fig.width=12}

mito.genes <- grep(pattern = "^mt-", x = rownames(mob164315@assays$Spatial), value = TRUE)
dropouts <- Matrix::colSums(mob164315@assays$Spatial@data == 0)/nrow(mob164315@assays$Spatial)
ribo.genes <- grep(pattern = "^Rp[sl]", x = rownames(mob164315@assays$Spatial), value = TRUE)
percent.mito <- Matrix::colSums(mob164315@assays$Spatial[mito.genes, ])/Matrix::colSums(mob164315@assays$Spatial)
percent.ribo <- Matrix::colSums(mob164315@assays$Spatial[ribo.genes, ])/Matrix::colSums(mob164315@assays$Spatial)
mob164315[['percent.mito']] <- percent.mito
mob164315[['percent.ribo']] <- percent.ribo
mob164315[['dropouts']] <- dropouts

VlnPlot(mob164315, features = c("nFeature_Spatial", "nCount_Spatial","dropouts","percent.ribo","percent.mito"), ncol=5, cols = "lightsteelblue3") + ggtitle("mob164315")

sum(mob164315@meta.data$nCount_Spatial)

```

# SCTransform normalization and clustering

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=6, fig.width=8}

mob164315 <- SCTransform(mob164315, assay = "Spatial", verbose = FALSE)
mob164315 <- RunPCA(mob164315, assay = "SCT", verbose = FALSE)
mob164315 <- RunUMAP(mob164315, reduction = "pca", dims = 1:30)
mob164315 <- FindNeighbors(mob164315, reduction = "pca", dims = 1:30)
mob164315 <- FindClusters(mob164315, verbose = FALSE, resolution = 0.4)

DimPlot(mob164315, reduction = "umap", label = TRUE) + ggtitle("mob164315")
SpatialDimPlot(mob164315, label = TRUE, label.size = 3, pt.size.factor = 3) + ggtitle("mob164315")

```

# Clusters re-labelling

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=6, fig.width=8}

new.cluster.ids <- c("Olfactory Nerve Layer (ONL)","Glomerular Layer (GL)","Granule Cell Layer (GCL+RMS)","Outer plexiform Layer (EPL)","Mitral Cell Layer (MCL)")
names(x = new.cluster.ids) <- levels(x = mob164315)
mob164315 <- RenameIdents(object = mob164315, new.cluster.ids)

my_levels <- c("Granule Cell Layer (GCL+RMS)","Mitral Cell Layer (MCL)","Outer plexiform Layer (EPL)","Glomerular Layer (GL)","Olfactory Nerve Layer (ONL)")
# Relevel object@ident
mob164315@active.ident <- factor(x = mob164315@active.ident, levels = my_levels)

#cell_type_color <- c("Granule Cell Layer (GCL+RMS)" = "#aea9ce",
#                     "Mitral Cell Layer (MCL)" = "#eb511a",
#                     "Outer plexiform Layer (EPL)" = "#ebd513",
#                     "Glomerular Layer (GL)" = "#56ba8f",
#                     "Olfactory Nerve Layer (ONL)" = "#466cb9")

SpatialDimPlot(mob164315, label = TRUE, label.size = 3, pt.size.factor =3) + ggtitle("mob164315")

```

# Gene Markers Heatmap

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=10, fig.width=8 }

DefaultAssay(object = mob164315) <- "SCT"
mob164315 <- ScaleData(object = mob164315, verbose = FALSE)
markers <- FindAllMarkers(object = mob164315, only.pos = TRUE)
top <- markers %>% group_by(cluster) %>% top_n(15, avg_logFC)
DoHeatmap(mob164315, features=top$gene, size=3.5)

write.table(markers, file="output/mob164315.markers.csv", sep=",")

```

# Correlation between clusters

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=6, fig.width=8}

mob164315@meta.data$ClusterName <- mob164315@active.ident

mnmat <- c()
uniq <- unique(mob164315@active.ident)
for(i in 1:length(uniq)){
  mnmat <- cbind(mnmat, apply(as.matrix(mob164315@assays$SCT@data[, mob164315@meta.data$ClusterName==uniq[i]]), 1, mean))
}

colnames(mnmat) <- as.vector(unique(mob164315@active.ident))
ct=cor(mnmat)
pheatmap(ct)

```

# Gene Markers Visualization

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=6, fig.width=12 }

SpatialFeaturePlot(mob164315, features = c("Fabp7","Nnat","Apod"), ncol=3, pt.size.factor =2)
SpatialFeaturePlot(mob164315, features = c("Nrsn1","Calb2","Eomes"), ncol=3, pt.size.factor =2)
SpatialFeaturePlot(mob164315, features = c("Bc1","Cnot3","Slc1a2"), ncol=3, pt.size.factor =2)
SpatialFeaturePlot(mob164315, features = c("Shisa3","Thy1","Reln"), ncol=3, pt.size.factor =2)
SpatialFeaturePlot(mob164315, features = c("Meis2","Nrgn","Sept4"), ncol=3, pt.size.factor =2)

```

# Integration of external data (Tepe et al., Cell report, 2018) (GSE121891)

```{r message=FALSE, warning=FALSE, echo=FALSE, eval=T, fig.height=6, fig.width=8}

#raw_counts<-read.table(file=paste0("/data/10x_data/10x_visium/ressources/","GSE121891_OB_6_runs_processed_seurat.dge.csv"),sep=",")
#raw_counts[1:5,1:5]
#metadata<-read.table(file=paste0("/data/10x_data/10x_visium/ressources/","GSE121891_OB_metaData_seurat.csv"),sep=",", header=TRUE)
#rownames(metadata) <- metadata$X
#metadata <- metadata[,-c(1)]
#metadata[1:5,1:7]
#gse <- CreateSeuratObject(raw_counts, project = "GSE121891", assay = "RNA", meta.data = metadata)
#gse <- SCTransform(gse, ncells = 3000, verbose = FALSE) %>% RunPCA(verbose = FALSE) %>% RunUMAP(dims = 1:30)
#saveRDS(gse, "./output/tepe.rds")

tepe <- readRDS("./output/tepe.rds")
DimPlot(tepe, group.by = "ClusterName", label = TRUE)
anchors <- FindTransferAnchors(reference = tepe, query = mob164315, normalization.method = "SCT")
predictions.assay <- TransferData(anchorset = anchors, refdata = tepe$ClusterName, prediction.assay = TRUE,  weight.reduction = mob164315[["pca"]])
mob164315[["predictions"]] <- predictions.assay

mob164315 <- FindSpatiallyVariableFeatures(mob164315, assay = "predictions", features = rownames(mob164315@assays$predictions@data), r.metric = 5, slot = "data", selection.method = "markvariogram")

DefaultAssay(mob164315) <- "predictions"
DotPlot(mob164315, features = sort(rownames(mob164315@assays$predictions@data))) + RotatedAxis()

SpatialFeaturePlot(mob164315, features = c("OEC2","OEC3","OEC4"), pt.size.factor = 1, ncol = 3, alpha = c(0.1, 1))
SpatialFeaturePlot(mob164315, features = c("N13", "N5"), pt.size.factor = 1, ncol = 3, alpha = c(0.1, 1))
SpatialFeaturePlot(mob164315, features = c("N3", "N1"), pt.size.factor = 1, ncol = 3, alpha = c(0.1, 1))
SpatialFeaturePlot(mob164315, features = c("N14", "N15"), pt.size.factor = 1, ncol = 3, alpha = c(0.1, 1))
SpatialFeaturePlot(mob164315, features = c("N10", "N9", "N8"), pt.size.factor = 1, ncol = 3, alpha = c(0.1, 1))
SpatialFeaturePlot(mob164315, features = c("Astro1","Astro2","Astro3"), pt.size.factor = 1, ncol = 3, alpha = c(0.1, 1))

DoHeatmap(mob164315, features= rownames(mob164315@assays$predictions@data), size=3.5, slot="data")

saveRDS(mob164315, "./output/mob164315.rds")

```

# Session Info

```{r sessinf}
sessionInfo()
```

